#!/bin/bash

#SBATCH --job-name=mapping_tests
#SBATCH --time=0-00:30:00
#SBATCH -pTHIN
#SBATCH -n48
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH -N2

OPERATION=$1
ALGORITHMS=("${@:2}")
./mapping_variation.sh "thin" 48 $OPERATION $ALGORITHMS
