#!/bin/bash

#SBATCH --job-name=_
#SBATCH --time=0-00:05:00
#SBATCH -pTHIN
#SBATCH -n24
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH -N1

message_size=$1

./point-to-point.sh 24 $message_size 
