#!/bin/bash

#SBATCH --job-name=_
#SBATCH --time=0-00:00:10
#SBATCH -pTHIN
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH -N1

module load hwloc/2.10.0
lstopo --no-default-legend thin.pdf
# lscpu > "thin.txt"
magick thin.svg thin.png
rm thin.svg
