#!/bin/bash

#SBATCH --job-name=_
#SBATCH --time=0-00:05:00
#SBATCH -pTHIN
#SBATCH -n48
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH -N2

MAPPINGS=("core" "L3cache" "numa" "socket" "node")

for M in "${MAPPINGS[@]}"
do
    mpirun --map-by $M -np 48 ./mapping_ranks_to_id "$M_mapping"
done
