#!/bin/bash

#SBATCH --job-name=_
#SBATCH --time=0-01:00:00
#SBATCH -pTHIN
#SBATCH -n48
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH -N2

repetitions=$1
operation=$2
algorithms=("${@:3}")
./run.sh "thin" 48 $repetitions $operation $algorithms
