#!/bin/bash

#SBATCH --job-name=iterations_test
#SBATCH --time=0-00:20:00
#SBATCH -pTHIN
#SBATCH -n48
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH -N2

repetitions=$1
./iters_warmup_variation.sh "THIN" 48 $repetitions
